- name: Auto-restart Nginx service
  hosts: localhost
  connection: local
  tasks:
    - name: Try to start nginx container
      shell: docker start nginx
      ignore_errors: yes

    - name: Run nginx container if not running
      shell: docker ps -q -f name=nginx || docker run -d --name nginx -p 8082:80 nginx

